
name: Node CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20


      - run: npm install
      - run: npm test   


      

      - name: deply  to docker hub
        run:  echo "${{DOCKER_PASSWORD}}" | docker login  -u "${{DOCKER_USERNAME}}" --password-stdin


      - name: Create Docker Image
        run: |
         docker build -t allanocodes/notes-app:1.0.0 .
    

      - name: create latest tag
        run: |
         docker tag allanocodes/notes-app:1.0.0 allanocodes/notes-app:latest
         

      - name: push image to docker hub
        run: |
          docker push allanocodes/notes-app:latest
          docker push allanocodes/notes-app:1.0.0


        